# Netlify configuration for Pixeltable docs
[build]
  base = "docs2"
  publish = "."
  command = "echo 'No build needed - serving static files'"

[build.environment]
  NODE_VERSION = "18"

# Deploy previews for all branches and PRs  
[context.deploy-preview]
  command = "echo 'No build needed - serving static files'"

[context.branch-deploy]
  command = "echo 'No build needed - serving static files'"

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"