/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a "previous" and "next" navigation
 - create a category with a generated index page

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the filesystem, or explicitly defined here.
  tutorialSidebar: [
    {
      type: 'category',
      label: '❦ Get Started',
      items: [
        'get-started/overview',
        'get-started/installation', 
        'get-started/quickstart'
      ],
    },
    {
      type: 'category',
      label: '✦ Examples',
      items: [
        'examples',
        {
          type: 'autogenerated',
          dirName: 'examples'
        }
      ],
    },
    {
      type: 'category',
      label: '📓 Jupyter Notebooks',
      items: [
        {
          type: 'category',
          label: 'Getting Started',
          items: [
            'jupyter/pixeltable-basics'
          ],
        },
        {
          type: 'category',
          label: 'AI/ML Integration',
          items: [
            'jupyter/working-with-hugging-face'
          ],
        },
        {
          type: 'category',
          label: 'Multimodal Applications',
          items: [
            'jupyter/audio-transcriptions',
            'jupyter/embedding-indexes',
            'jupyter/rag-demo',
            'jupyter/rag-operations'
          ],
        },
        {
          type: 'category',
          label: 'Advanced Features',
          items: [
            'jupyter/udfs-in-pixeltable',
            'jupyter/working-with-external-files'
          ],
        }
      ],
    },
    {
      type: 'category',
      label: '✧ Support',
      items: [
        'support/overview'
      ],
    },
  ],
  
  // SDK Reference sidebar
  sdkSidebar: [
    'sdk/index',
    {
      type: 'category',
      label: 'Core API',
      items: [
        'sdk/core/index',
        'sdk/core/core'
      ],
    },
    {
      type: 'category',
      label: 'Functions',
      items: [
        'sdk/functions/index',
        'sdk/functions/functions',
        'sdk/functions/functions-anthropic',
        'sdk/functions/functions-audio',
        'sdk/functions/functions-bedrock',
        'sdk/functions/functions-date',
        'sdk/functions/functions-image',
        'sdk/functions/functions-math',
        'sdk/functions/functions-openai',
        'sdk/functions/functions-video'
      ],
    },
    {
      type: 'category',
      label: 'Input/Output',
      items: [
        'sdk/io/index',
        'sdk/io/io'
      ],
    },
    {
      type: 'category',
      label: 'Iterators',
      items: [
        'sdk/iterators/index',
        'sdk/iterators/iterators'
      ],
    },
    {
      type: 'category',
      label: 'Extensions',
      items: [
        'sdk/ext/index',
        'sdk/ext/ext',
        'sdk/ext/ext-functions',
        'sdk/ext/ext-functions-whisperx',
        'sdk/ext/ext-functions-yolox'
      ],
    }
  ],
};

export default sidebars;
